name: Continous integration
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build_and_lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install commitlint
      run: |
        npm install -g conventional-changelog-conventionalcommits
        npm install -g commitlint@latest
    
    - name: Install dependancies and build
      run: |
            if [ -f package.json ]; then
                npm ci
                npm run build
            else
                echo "package.json not found, skipping build step"
            fi
      shell: bash

    - name: Validate commit messages
      if: github.event_name == 'push'
      run: npx commitlint --from HEAD~1 --to HEAD --verbose

    - name: Validate PR commits with commitlint
      if: github.event_name == 'pull_request'
      run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
